//! Strategy contracts.
pub mod auth_strategy;
pub mod aws_strategy;
pub mod basic_strategy;
pub mod bearer_strategy;
pub mod header_strategy;
pub mod helper;
pub mod strategy;
pub mod strategy_factory;
pub use auth_strategy::AuthStrategy;
